name: Build
on:
  - push


env:
  LOTUS_PATH: ~/.lotus-local-net
  LOTUS_MINER_PATH: ~/.lotus-miner-local-net
  LOTUS_SKIP_GENESIS_CHECK: _yes_
  CGO_CFLAGS_ALLOW: "-D__BLST_PORTABLE__"
  CGO_CFLAGS: "-D__BLST_PORTABLE__"

jobs:
  build:
    timeout-minutes: 5
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
      - name: Install yarn
        run: |
          npm install -g yarn
      - run: yarn install
      - run: yarn asbuild
        name: Install Hello Actor in Lotus
      - run: |
          ~/lotus/lotus version
          ~/lotus/lotus chain install-actor build/debug.wasm >> output.txt
          cat output.txt
      - run: |
          cid=$(sed -n 's/^Actor Code CID: //p' output.txt)
          echo $cid
          ~/lotus/lotus chain create-actor $cid
