name: "Benchmark release"
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  benchmark:
    name: "Benchmark"
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      VERDACCIO_TOKEN: ${{ secrets.VERDACCIO_READ_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-03-31
          override: true
      - name: Install golang
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Restore crates
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('./benchmarking/Cargo.lock') }}
      - name: Set npmrc
        run: |
          yarn config set @zondax:registry https://verdaccio.zondax.net/
          npm config set //verdaccio.zondax.net/:_authToken "$VERDACCIO_TOKEN"
          npm config set //verdaccio.zondax.net/:always-auth true
      - name: Test WASM on Rust VM
        run: |
          cd benchmarking
          sudo apt-get install tree
          rustup target add wasm32-unknown-unknown
          make install
          make install-llvm-ci
          make install-tinygo
          make benchmark
      - name: "Save results"
        uses: actions/upload-artifact@v3
        with:
          name: benchmark_results
          path: ./benchmarking/benchmark_results.csv
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./benchmarking/benchmark_results.csv
      - name: Save crates
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('./benchmarking/Cargo.lock') }}
